2019-12-18 16:15:56,341 - error_logger - ERROR - exception Can't move left when robot is at the position (0, 1)
2020-02-25 22:00:25,138 - error_logger - ERROR - exception 
**********************************************************************
  Resource [93mwordnet[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('wordnet')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/wordnet[0m

  Searched in:
    - '/Users/gavran/nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../share/nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

2020-02-25 22:07:52,015 - error_logger - ERROR - exception 
**********************************************************************
  Resource [93mwordnet[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('wordnet')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/wordnet[0m

  Searched in:
    - '/Users/gavran/nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../share/nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

2020-02-25 22:09:42,393 - error_logger - ERROR - exception 
**********************************************************************
  Resource [93mwordnet[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('wordnet')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/wordnet[0m

  Searched in:
    - '/Users/gavran/nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../share/nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

2020-02-25 22:10:41,767 - error_logger - ERROR - exception 
**********************************************************************
  Resource [93mwordnet[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('wordnet')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/wordnet[0m

  Searched in:
    - '/Users/gavran/nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../share/nltk_data'
    - '/Users/gavran/.virtualenvs/exampleServer/bin/../lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

2020-04-08 15:31:12,914 - error_logger - ERROR - exception 
2020-04-08 15:35:22,982 - error_logger - ERROR - exception 
2020-04-09 15:53:20,222 - error_logger - ERROR - exception 
2020-04-09 15:53:44,848 - error_logger - ERROR - exception Can't move down when robot is at the position (0, 0)
2020-04-09 16:07:00,896 - error_logger - ERROR - exception 
2020-04-09 16:11:05,054 - error_logger - ERROR - exception 
2020-04-09 16:12:18,100 - error_logger - ERROR - exception 
2020-04-09 16:13:36,205 - error_logger - ERROR - exception 
2020-04-09 16:14:38,302 - error_logger - ERROR - exception 
2020-04-09 16:21:41,172 - error_logger - ERROR - exception 'str' object has no attribute 'write'
2020-04-10 19:26:40,954 - error_logger - ERROR - exception list index out of range
2020-04-10 19:30:04,920 - error_logger - ERROR - exception list index out of range
2020-04-24 18:09:05,914 - error_logger - ERROR - exception Can't move down when robot is at the position (0, 0)
2020-05-06 12:45:57,705 - error_logger - ERROR - exception 
2020-05-06 12:46:44,693 - error_logger - ERROR - exception 
2020-05-13 13:28:33,538 - error_logger - ERROR - exception (0, 'pick_one_green_circle_item')
2020-05-13 13:29:20,562 - error_logger - ERROR - exception (0, 'pick_one_yellow_square_item')
2020-05-13 13:34:58,626 - error_logger - ERROR - exception (0, 'pick_one_x_x_item')
2020-05-13 13:35:39,496 - error_logger - ERROR - exception (0, 'pick_one_x_x_item')
2020-05-13 13:39:10,263 - error_logger - ERROR - exception (0, 'pick_one_green_square_item')
2020-05-13 13:40:11,464 - error_logger - ERROR - exception (0, 'pick_one_green_square_item')
2020-05-13 13:42:03,317 - error_logger - ERROR - exception 
2020-05-13 13:44:11,441 - error_logger - ERROR - exception 
2020-05-13 13:44:55,066 - error_logger - ERROR - exception 
2020-05-13 13:46:08,444 - error_logger - ERROR - exception 
2020-05-21 13:24:40,709 - error_logger - ERROR - exception 'ExperimentTraces' object has no attribute 'hints_with_weights'
2020-05-21 13:25:54,629 - error_logger - ERROR - exception 'ExperimentTraces' object has no attribute 'hints_with_weights'
2020-05-21 13:27:57,544 - error_logger - ERROR - exception 'module' object is not callable
2020-05-21 13:29:57,209 - error_logger - ERROR - exception 
2020-05-21 13:33:05,962 - error_logger - ERROR - exception 'module' object is not callable
2020-05-21 13:34:24,664 - error_logger - ERROR - exception 
